# Ordering table descendaly according to MSH2 hotspot variants
custom_plot_config:
  MSH2_hotspot_varcount:
    defaultsort:
      - column: "MSH2_c.942+3A>T"
        direction: desc
      - column: "MSH2_c.942+2T>A"
        direction: desc
      - column: "MSH2_c.942+2T>G"
        direction: desc
      - column: "MSH2_c.942+2T>C"
        direction: desc

# Defining threshold for MSH2 hotspot variants need for Sanger sequencing
MSH2_hotspot_varcount_config:
  sanger_threshold : 20

# Assigning modules to run
run_modules:
  - MSH2_hotspot_varcount
  
# Assigning template
template: "cmgg"