custom_plot_config:
  MSH2_hotspot_varcount:
    defaultsort:
      - column: "MSH2_c.942+3A>T"
        direction: desc
      - column: "MSH2_c.942+2T>A"
        direction: desc
      - column: "MSH2_c.942+2T>G"
        direction: desc
      - column: "MSH2_c.942+2T>C"
        direction: desc

MSH2_hotspot_varcount_config:
  sanger_threshold : 20

run_modules:
  - MSH2_hotspot_varcount

template: "cmgg"