#!/usr/bin/env python
"""MultiQC example plugin functions

We can add any custom Python functions here and call them
using the setuptools plugin hooks.
"""

from __future__ import print_function

from multiqc import config
import importlib_metadata
import logging

# Initialise the main MultiQC logger
log = logging.getLogger("multiqc")


# Add default config options for the things that are used in MultiQC_NGI
def plugin_execution_start():
    """Code to execute after the config files and
    command line flags have been parsedself.

    This setuptools hook is the earliest that will be able
    to use custom command line flags.
    """

    # Plugin's version number defined in pyproject.toml:
    version = importlib_metadata.version("multiqc_cmgg")
    log.info(f"Running Example MultiQC Plugin v{version}")

    # Add to the main MultiQC config object.
    # User config files have already been loaded at this point
    #   so we check whether the value is already set. This is to avoid
    #   clobbering values that have been customised by users.

    if config.kwargs.get("disable_plugin", False):
        log.info("Plugin is disabled")
        return None

    log.debug("CMGG - Updating config")
    # Add module to module order
    config.module_order.extend(["sample_gender","coverage"])
     # Move module to the top
    config.top_modules.extend(["sample_gender","coverage"])

    
    # Add to the search patterns used by modules
    # Sample_gender search patterns    
    if "sample_gender/xy" not in config.sp:
        config.update_dict(config.sp, {"sample_gender/xy": {"fn": "*_xy.tsv","shared":False}})
        log.info(f"sample_gender/xy pattern: {config.sp.get('sample_gender/xy')}")

    if "sample_gender/hetx" not in config.sp:
        config.update_dict(config.sp, {"sample_gender/hetx": {"fn": "*_hetx.tsv","shared":False}})

    if "sample_gender/sry" not in config.sp:
        config.update_dict(config.sp, {"sample_gender/sry": {"fn": "*_sry.tsv","shared":False}})

    ## Coverage search patterrns
    if "coverage/summary" not in config.sp:
        config.update_dict(config.sp,{"coverage/summary":{"fn":"*.mosdepth.summary.txt","shared":False}})

    if "coverage/global_dist" not in config.sp:
        config.update_dict(config.sp,{"coverage/global_dist":{"fn":"*.mosdepth.global.dist.txt","shared":False}})

    if "coverage/region_dist" not in config.sp:
        config.update_dict(config.sp,{"coverage/region_dist":{"fn":"*.mosdepth.region.dist.txt","shared":False}})    
    # adds mosdepth_config to multiqc config file
    if "mosdepth_config" not in config:
        config.update_dict(config,{"mosdepth_config":{"general_stats_coverage":[1,5,10,20,30,40,50,60,70,80,90,100],"mosdepth_config":{"general_stats_coverage_hidden":[1,5,10,20,30,40,50,60,70,80,90,100]}}}) 
        
    # Some additional filename cleaning
    # config.fn_clean_exts.extend([".my_tool_extension", ".removeMetoo"])

    # Ignore some files generated by the custom pipeline
    # config.fn_ignore_paths.extend(
    #     [
    #         "*/my_awesome_pipeline/fake_news/*",
    #         "*/my_awesome_pipeline/red_herrings/*",
    #         "*/my_awesome_pipeline/noisy_data/*",
    #         "*/my_awesome_pipeline/rubbish/*",
    #     ]
    # )