name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build . -t thomstev/multiqc_cmgg:0.0.2dev
      - name: Push image to quay.io
        run: |
          docker login quay.io -u thomstev+github_actions -p ${{secrets.QUAY_TOKEN}}
          docker push quay.io/thomstev/multiqc_cmgg:0.0.2dev
