name: Build and Publish image to Quay.io
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get latest MultiQC tag
        id: get_tag
        run: |
          TAG=$(curl -s https://quay.io/api/v1/repository/biocontainers/multiqc/tag/?limit=1 | jq -r '.tags[0].name')
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --build-arg MULTIQC_TAG=${{ env.LATEST_TAG }} -t quay.io/thomstev/multiqc_cmgg:0.0.2dev

      - name: Login and Push image to quay.io
        run: |
          docker login quay.io -u thomstev+github_actions -p ${{secrets.QUAY_TOKEN}}
          docker push quay.io/thomstev/multiqc_cmgg:0.0.2dev
